# This workflow encompasses actions necessary to deploy new changes to the SMTM FE
# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

name: SMTM FE Deployment Workflow

on:
  push:
    branches: [ "main" ]
    
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
  deploy-prod:
    permissions: 
      id-token: write
      issues: write
      contents: read
      
    name: Deploy Prod
    runs-on: ubuntu-latest
    environment: 'Prod'
    needs: [deploy-staging]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Manual Approval Step
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: michelle-smtm, sonali-smtm, JeremyKritz-smtm, cameron-smtm
        minimum-approvals: 1
        issue-title: "Deploying to prod from beta"
        issue-body: "Please approve or deny the deployment"
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::836899195270:role/github-oidc-role
        role-session-name: GithubActionsCdkSession
    - name: Run CDK Deployment
      id: run-cdk-diff
      run: |
        cd smtm-cdk
        npm install -g aws-cdk
        npm install
        npm run build
        cdk deploy SmtmCdkStack-prod --require-approval=never --verbose