name: SMTM Frontend Cypress Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5.8.3
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          SMTM_BACKEND_URL: ${{ secrets.SMTM_BACKEND_URL }}
          SMTM_OPENAI_URL: ${{ secrets.SMTM_OPENAI_URL }}
          SMTM_OPENAI_API_KEY: ${{ secrets.SMTM_OPENAI_API_KEY }}
          SMTM_USER_JANE_DOE: ${{ secrets.SMTM_USER_JANE_DOE }}
          SMTM_PASSWORD_JANE_DOE: ${{ secrets.SMTM_PASSWORD_JANE_DOE }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          DEBUG: "@cypress/github-action"
        with:
          browser: chrome
          headed: true
          start: npm run dev
          wait-on: "http://localhost:3000"