# This workflow encompasses actions necessary to deploy new changes to the SMTM FE
# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

name: SMTM FE Deployment Workflow

on:
  push:
    branches: [ "staging" ]
    
env:
  CUSTOM_GITHUB_ACCESS_TOKEN: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}

jobs:
  deploy-prod:
    permissions: 
      id-token: write
      issues: write
      contents: read
      
    name: Deploy Prod
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Manual Approval Step
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}
        approvers: michelle-smtm
        minimum-approvals: 1
        issue-title: "Deploying to prod from beta"
        issue-body: "Please approve or deny the deployment"
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''
    - name: git checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}

    # https://github.com/marketplace/actions/github-pull-request-action
    - name: create pull request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ github.TOKEN }}
        destination_branch: ${{ github.event.repository.default_branch }}
        pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
        pr_body: "Automated Pull Request"
        pr_reviewer: "robot"
        pr_assignee: "robot"

    # https://github.com/marketplace/actions/enable-pull-request-automerge
    - name: enable automerge
      if: steps.open-pr.outputs.pr_number != ''
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}
        pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
        merge-method: merge