# This workflow encompasses actions necessary to deploy new changes to the SMTM FE
# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

name: SMTM FE Deployment Workflow

on:
  push:
    branches: [ "staging" ]
    
env:
  CUSTOM_GITHUB_ACCESS_TOKEN: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}

jobs:
  deploy-prod:
    permissions: 
      id-token: write
      issues: write
      contents: read
      pull-requests: write
      
    name: Deploy Prod
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Manual Approval Step
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}
        approvers: michelle-smtm
        minimum-approvals: 1
        issue-title: "Deploying to prod from staging"
        issue-body: "Please approve or deny the deployment"
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Merge into main
      uses: mtanzi/action-automerge@v1
      id: merge
      with:
        github_token: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}
        source: 'staging'
        target: 'main'
        webhook_url: #if present add the Slack webhook
  