# This workflow encompasses actions necessary to deploy new changes to the SMTM
# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
name: SMTM FE Deployment Workflow

on:
  push:
    branches: [ "staging" ]
    
env:
  CUSTOM_GITHUB_ACCESS_TOKEN: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: skip-workflow
        id: skip-workflow 
        uses: saulmaldonado/skip-workflow@v1
        with:
          phrase: '[skip-cypress]'
          github-token: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}
      - name: Cypress run
        if: ${{ !steps.skip-workflow.outputs.skip }}
        uses: cypress-io/github-action@v5.8.3
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          SMTM_BACKEND_URL: ${{ secrets.SMTM_BACKEND_URL }}
          SMTM_OPENAI_URL: ${{ secrets.SMTM_OPENAI_URL }}
          SMTM_OPENAI_API_KEY: ${{ secrets.SMTM_OPENAI_API_KEY }}
          SMTM_USER_JANE_DOE: ${{ secrets.SMTM_USER_JANE_DOE }}
          SMTM_PASSWORD_JANE_DOE: ${{ secrets.SMTM_PASSWORD_JANE_DOE }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          DEBUG: "@cypress/github-action"
        with:
          browser: chrome
          headed: true
          start: npm run dev
          wait-on: "http://localhost:3000"
  deploy-prod:
    permissions: 
      id-token: write
      issues: write
      contents: read
      
    name: Deploy Prod
    runs-on: ubuntu-latest
    needs: [cypress]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Manual Approval Step
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}
        approvers: michelle-smtm
        minimum-approvals: 1
        issue-title: "Deploying to prod from staging"
        issue-body: "Please approve or deny the deployment"
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Merge into main
      uses: mtanzi/action-automerge@v1
      id: merge
      with:
        github_token: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}
        source: 'staging'
        target: 'main'
        webhook_url:
  