# This workflow encompasses actions necessary to deploy new changes to the SMTM FE
# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

name: SMTM FE Deployment Workflow

on:
  push:
    branches: [ "staging" ]
    
env:
  CUSTOM_GITHUB_ACCESS_TOKEN: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}

jobs:
  deploy-prod:
    permissions: 
      id-token: write
      issues: write
      contents: read
      pull-requests: write
      
    name: Deploy Prod
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Manual Approval Step
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}
        approvers: michelle-smtm
        minimum-approvals: 1
        issue-title: "Deploying to prod from staging"
        issue-body: "Please approve or deny the deployment"
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}
    # https://github.com/marketplace/actions/pull-request-action-github-cli
    - name: Create PR
      uses: peter-evans/create-pull-request@v5
      id: cpr
      with:
        base: "main"
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }} 
    - uses: hmarr/auto-approve-action@v3
      with:
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
    # # https://github.com/marketplace/actions/enable-pull-request-automerge
    - name: enable automerge
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.CUSTOM_GITHUB_ACCESS_TOKEN }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: merge