# This workflow encompasses actions necessary to deploy new changes to the SMTM FE
# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

name: SMTM FE Deployment Workflow

on:
  push:
    branches: [ "staging" ]
    
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
  deploy-prod:
    permissions: 
      id-token: write
      issues: write
      contents: read
      
    name: Deploy Prod
    runs-on: ubuntu-latest
    needs: [deploy-staging]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Manual Approval Step
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: michelle-smtm
        minimum-approvals: 1
        issue-title: "Deploying to prod from beta"
        issue-body: "Please approve or deny the deployment"
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''
    - name: git checkout
      uses: actions/checkout@v3
      with:
        token: ${{ github.TOKEN }}

    # https://github.com/marketplace/actions/github-pull-request-action
    - name: create pull request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ github.TOKEN }}
        destination_branch: ${{ github.event.repository.default_branch }}
        pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
        pr_body: "Automated Pull Request"
        pr_reviewer: "robot"
        pr_assignee: "robot"

    # https://github.com/marketplace/actions/enable-pull-request-automerge
    - name: enable automerge
      if: steps.open-pr.outputs.pr_number != ''
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ github.TOKEN }}
        pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
        merge-method: merge